##############################
# Default Shell
##############################
set-option -g default-shell /bin/zsh

##############################
# Prefix Key
##############################
unbind C-b
set-option -g prefix C-q
bind-key C-q send-prefix

##############################
# Options
##############################

# Reload tmux config
bind e source-file ~/.tmux.conf

set -g mouse on
set -s escape-time 0

# Extended keys (shift+enter, ctrl+arrows w/ modifiers, etc.)
set -s extended-keys always
set -as terminal-features 'xterm*:extkeys'
set -as terminal-features 'kitty*:extkeys'

# Use 256color
set -g default-terminal "tmux-256color"
set -sg terminal-overrides ",*:RGB"

# Set status bar background to terminal colour
set -g status-style bg=terminal

# Increase status-left-length (default is 10)
set -g status-left-length 50
# Increase status-right-length (default is 40)
set -g status-right-length 150
# Refresh status bar every 1 second (default is 15)
set -g status-interval 1

# StatusBar Layout
set -g status-justify left

##############################
# Pane Titles
##############################
set -g pane-border-status top
set -g pane-border-format " #[bold]#{pane_index}#[nobold]: #{?pane_title,#{pane_title},#{pane_current_command}} "
bind T command-prompt -p "Pane title:" 'select-pane -T "%%"'

##############################
# Navigation
##############################

# Movement with vimkeys
source-file ~/.tmux_vim_nav.conf

# Equalise pane sizes (like Ctrl-W = in vim)
bind = select-layout tiled

# Split panes with vimkeys
unbind %
unbind '"'
bind v split-window -h -c '#{pane_current_path}'
bind s split-window -v -c '#{pane_current_path}'

# Scratchpad session popup
bind o display-popup -w 70% -h 70% -E "tmux new-session -A -s scratch"

# Git session popup
bind g display-popup -d '#{pane_current_path}' -w 70% -h 70% -E

# Session jumper popup
bind r display-popup -w 90% -h 90% -E "tmux list-sessions | sed 's/:.*$//' | fzf --reverse --preview 'tmux capture-pane -ept {} | tail -50' --preview-window=down:70% | xargs tmux switch-client -t"

# switch to last session
bind b switch-client -l

# Pane jumper popup
# bind f display-popup -E "tmux list-windows | sed -E 's/[0-9]+: ([^ ]+).*$/\\1/' | fzf --reverse --preview \"tmux capture-pane -pt {}\" | xargs tmux switch-window -t"


##############################
# Plugins
##############################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run "~/.tmux/plugins/tpm/tpm"

##############################
# Theme
##############################
source-file ~/dots/tmux/current-theme.conf
