set -g pane-border-style fg=blue
set -g pane-active-border-style fg=magenta

set -g status-left "#[fg=black,bg=blue,bold] #S #[fg=blue,bg=terminal,nobold,noitalics,nounderscore]"
set -g status-right "#{prefix_highlight}#[fg=brightblack,bg=terminal,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] #(gcloud config get-value project 2>/dev/null || echo 'no gcloud project') #[fg=cyan,bg=brightblack,nobold,noitalics,nounderscore]#[fg=black,bg=cyan,bold] #H "

set -g window-status-format "#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I #[fg=white,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#W #F #[fg=brightblack,bg=terminal,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #F #[fg=cyan,bg=terminal,nobold,noitalics,nounderscore]"
set -g window-status-separator ""
