set -g pane-border-style "fg=#D1C7C3"
set -g pane-active-border-style "fg=#B2A39B"

set -g status-left "#[fg=#564E4A,bg=#B2A39B,bold] #S #[fg=#B2A39B,bg=terminal,nobold,noitalics,nounderscore]"
set -g status-right "#{prefix_highlight}#[fg=#D1C7C3,bg=terminal,nobold,noitalics,nounderscore]#[fg=#564E4A,bg=#D1C7C3] #(gcloud config get-value project 2>/dev/null || echo 'no gcloud project') #[fg=#B2A39B,bg=#D1C7C3,nobold,noitalics,nounderscore]#[fg=#564E4A,bg=#B2A39B,bold] #H "

set -g window-status-format "#[fg=black,bg=#D1C7C3,nobold,noitalics,nounderscore] #[fg=#564E4A,bg=#D1C7C3]#I #[fg=#564E4A,bg=#D1C7C3,nobold,noitalics,nounderscore] #[fg=#564E4A,bg=#D1C7C3]#W #F #[fg=#D1C7C3,bg=terminal,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=#B2A39B,nobold,noitalics,nounderscore] #[fg=#564E4A,bg=#B2A39B]#I #[fg=#564E4A,bg=#B2A39B,nobold,noitalics,nounderscore] #[fg=#564E4A,bg=#B2A39B]#W #F #[fg=#B2A39B,bg=terminal,nobold,noitalics,nounderscore]"
set -g window-status-separator ""
